source 'http://rubygems.org'
gem 'googlevoiceapi'
gem 'chronic'
gem 'mongo'
gem 'rest-client'
gem 'activesupport', '3.2.14'
gem 'rspec'
gem 'typhoeus'
gem 'mandrill-api'
gem 'redis'
gem 'htmlentities'
